services:

  netflix_mariadb:
    image: mariadb:10.11.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  netflix_nginx:
    build: nginx/
    volumes:
      - /data:/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  netflix_backend:
    build: backend/
    depends_on:
      - netflix_mariadb
      - netflix_nginx
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

