services:

  netflix_mariadb:
    image: mariadb:10.11.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  netflix_cassandra:
    image: cassandra:4.1.3
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra 