# Use the official NGINX image as the base image
FROM nginx:latest

# Copy your nginx.conf file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the entire "data" folder from your host into the root directory of the container
# RUN mkdir /data
# COPY /data /data